// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSSf8LIQ8bJGxCA55dYnBgLrvZezcYryY',
    appId: '1:803527869696:web:957f1264711137d5f79fe5',
    messagingSenderId: '803527869696',
    projectId: 'plenus-acd5a',
    authDomain: 'plenus-acd5a.firebaseapp.com',
    storageBucket: 'plenus-acd5a.firebasestorage.app',
    measurementId: 'G-H1QS1TE1MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBurekl-xsGttHtxTpVmtE1wqIQ4kfsJJY',
    appId: '1:803527869696:android:a1b16033ab906c59f79fe5',
    messagingSenderId: '803527869696',
    projectId: 'plenus-acd5a',
    storageBucket: 'plenus-acd5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEqxlioQt3z7MRXBRPYQlrJMFrlTloyzI',
    appId: '1:803527869696:ios:c7571336b801a0d3f79fe5',
    messagingSenderId: '803527869696',
    projectId: 'plenus-acd5a',
    storageBucket: 'plenus-acd5a.firebasestorage.app',
    iosBundleId: 'com.example.teste',
  );
}
